### ISSUE TITLE
Display and Indexing of HTML-encoded characters

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/vatican_exhibits#375]
HTML-encoded characters (principally angle brackets) are being rendered correctly in the embedded Mirador, but not in the Spotlight text areas. See two examples below:

Dear Ben,
a couple of  examples of  the issue on angle brackets:

http://spotlight.bav.local/palimpsests/catalog/172cbdc1-319e-4edf-abdf-f70890ef9151

In section: 
Ar-v, p. 1-302 Augustinus: Enarrationes in Psalmos CIX–CXL, p. 143-161 Enarratio in Psalmum CXXX, and p. 1-302 &lt;inf.&gt; M. Tulli Ciceronis De re publica

![1549989312463](https://user-images.githubusercontent.com/796990/52743048-0529d580-2f8e-11e9-8adb-4d7e8da0ef00.png)

or 
https://spotlight.vatlib.it/palimpsests/catalog/a4c436d4-48ed-415d-a7fb-2e2641c3ab93

Section:
1r-173r Iosephus, Flavius: Antiquitates Iudaicae libri XX, 1r-345v &lt;inf. 1&gt; Menologii praemetaphrastici Iunii mensis, and 169r + 169av, 169v + 169ar, 171r + 167v, 171v + 167r &lt;inf. 1&gt; Passio s. Iustini
![1549989427849](https://user-images.githubusercontent.com/796990/52742927-c6941b00-2f8d-11e9-85b6-1db3f093c776.png)

Many thanks in advance,
Paola

**Comment by mejackreed** [comment]
This is happening because we are rendering the text exactly as it appears in the IIIF manifest range label:

![Screen Shot 2019-06-20 at 7 05 11 AM](https://user-images.githubusercontent.com/1656824/59851419-d354c100-9329-11e9-8f9c-5146539dbf04.png)

https://digi.vatlib.it/iiif/MSS_Vat.gr.984/manifest.json

We shouldn't coerce this. It is also unclear to me whether or not `label` supports simple HTML (doesn't seem to). Closing this issue as a "Won't fix"

**Comment by blalbrit** [comment]
For phase 2 backlog.
