### ISSUE TITLE
Design project landing page

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#4]
Total of 6 exhibits (1 is the project itself)
Custom homepage with cards for each exhibit
Custom sidebar links
Vatican theming/branding

**Comment by blalbrit** [comment]
See https://digi.vatlib.it/mss/ for basic theming and palette.

**Comment by ggeisler** [comment]
Below are initial mockups to use as a basis for discussion with BAV. As with #10, I expect to go through multiple iterations of mockups + feedback to get to something final, so this is just a start. The header, footer, and color palette will change in coordination with any changes we make to those elements as part of #10.

The titles on the cards and the card images are just placeholders to make the page look somewhat realistic. I'd expect those to change as the project progresses.

Here are the things we'd want to talk to BAV about:

- What do they want to call the overall exhibit? And do they want to title it so that there is a title and a subtitle, as in my mockups?

- How do they want to use the sidebar area? Do they have a list of links they want to show here? Do they want to use more than one section in the sidebar (e.g., in SUL Exhibits we have two sections, the second of which is only seen by superadmins, though most of those links won't be relevant to the Vatican because they presumably won't be creating new exhibits over time).

- The cards point out the need to carefully consider the title and subtitle of each exhibit, both for how they appear on the cards and how they appear in the specific exhibit masthead.

- As we start working with the content of each exhibit, we should keep an eye out for canvases from each exhibit that would make for a good card image for the exhibit.

- Are we going to translate the project landing page? Our recent translation work did not provide for a way to translate this page, but there isn't too much to deal with on this page (the headings and text on each card will have translations available, based on the individual exhibit translations) so providing a way to show translated values is probably feasible.

### Initial landing page
<img width="720" alt="landing-page-v1" src="https://user-images.githubusercontent.com/101482/40866393-48854d1a-65b2-11e8-84b9-c57c821d27ec.png">

----

### Landing page where the user has selected a card
<img width="720" alt="landing-page-v1-flipped" src="https://user-images.githubusercontent.com/101482/40866420-60f11f5a-65b2-11e8-9301-6b66d9cf01d3.png">

**Comment by ggeisler** [comment]
Most of the pending questions related to the proposed design above will be resolved as part of #10. The landing page specific question we need an answer from the Vatican on is this one, discussed with Paola on 6/21 and asked in an email I just sent:

> The Spotlight landing page design allows for a full-height sidebar where we can list any links that you think might be helpful to pathway project users. The list in the mockup is just a guess as to what might be useful, so please provide the list of links you actually want to use.

**Comment by ggeisler** [comment]
I think things look good enough for now and if BAV wants changes in the future we can address them specifically then.
