### ISSUE TITLE
Figure out how to pass over mirador state to embeded mirador viewer

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/vatican_exhibits#93]
Discussed in https://github.com/sul-dlss/vatican_exhibits/pull/89

**Comment by aeschylus** [comment]
I see a few options we have for doing this. 

### 1. Pass the config into the Mirador tag
The simplest is probably to just **pass the config into the url**. As long as we keep the config small and don't try to put the full outputted `currentConfig` in the query parameter, we should be able to stay under the practical [URL length limit](https://stackoverflow.com/questions/29458445/what-is-a-safe-maximum-length-a-segment-in-a-url-path-should-be/33733386).

This also has the drawback of making it currently impossible to get any information back out of the instance, because of [mirador_rails/issues/10](https://github.com/sul-dlss/mirador_rails/issues/10). I've made an attempt to fix this in [this pr](https://github.com/sul-dlss/mirador_rails/pull/11), but would like to get feedback on that. The crux is that no instance variable is declared by the mirador_tag helper, so there is nothing to select out of the iframe's [contentWindow](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow) (its sandboxed javascript runtime). We are the parent page, so we can call down to the objects within the iframe as much as we want, but only if there is a way to get a handle on them.

### 2. Delete the entire mirador instance and re-initialise it from inside the iframe
`Mirador` (the "class" or library) is in the on the contentWindow object of the iframe, so we can always spawn a new Mirador instance later. This can be done without modifying the rails gem, but the initialised instance will continue to sit around in the iframe's javascript runtime for quite awhile. We would delete the DOM element and then append our own anew. Something about this feels wrong.

### 3. Load the instance blank, and load it up using the event system after locales have loaded
This will require something like: https://github.com/sul-dlss/mirador_rails/pull/11 being implemented.

By "load it blank", I mean just don't pass any options, so the instance will open no windows and request no manifests. We then use the event system to set up the instance from our config, from within the admin block. I like this option the best, as it provides the most control and keeps all the logic inside one JS file, which should make a plugin easier, as well as make the code easier to understand.

**Comment by aeschylus** [comment]
Mentioned in #6 (making sure this update shows up in that thread)

**Comment by jkeck** [comment]
I agree that Option 1 feels the best out of the three listed here.

**Comment by aeschylus** [comment]
Several additional options emerged during pairing. Option 1 above is still on the table, but there was some concern about putting the config in the URL bar. We are using the URL-based configuration on the display version of the page, but we may also want to reconsider that.

See: https://github.com/sul-dlss/vatican_exhibits/pull/160/files

The initial configuration is being passed as a javascript file in the asset pipeline, appending it to the mirador bundle. This causes it to load in the context of the iframe. This allows us to declare an instance name in the iframe context (bypassing the need to use the updated mirador_rails gem), and giving the configuration from the parent element ([minor issue](https://github.com/sul-dlss/vatican_exhibits/pull/160/files#r199235812) with this at the moment though).

I'm still in favour of option 1, but if we absolutely must avoid using the url parameters, I would suggest we explore doing a new release of Mirador that correctly interprets an element instead of a CSS id on initialisation, going with option 2 above, or implementing a hash/unique-id-based state saving feature.

**Comment by mejackreed** [comment]
Closing for now. Will reopen if we get free to address this and make cascading changes.
